<template>
  <div id="feed">
    <div class="container" style="display:flex;flex:4;margin:auto;justify-content:center;padding-top:20px">
      <span class="reaction-icon"><h5>Newest</h5></span>
      <span class="reaction-icon"><h5>Hottest</h5></span>
      <span class="reaction-icon"><h5>Mine</h5></span>
      
    </div>
    <div class="col  col-md-8 col-lg-6 center ml-auto mr-auto  " ar>

      <!-- BEGIN EACH OF THE CARDS -->
      <div  v-for="(startupCard, index) in startupCards" v-bind:key="startupCard.id">
        <div class="wholeCard " style="margin-top:10px" v-bind:id="startupCard.id">
          <div class="front-side card" style="display:inline-flex !important; min-width:200px">
            <div style="position:relative">
              <img class='card-img-top' style="width:100%;"
                src="https://assets.regus.com/images/nwp/homepage-product-co-working.jpg" alt="brand image">
              <div class="flag"></div>
            </div>
            <div class="card-body">
              <h4 class="card-title text-center">{{startupCard.brandTitle}}</h4>
              <p class="card-text text-center">{{startupCard.brandHeading}}</p>
            </div>
            <div class="container reaction-list" style="width:60%">
              <span class="far fa-heart reaction-icon" v-on:click="activateHeart(startupCard)"></span>
              <span class="far fa-comment-dots reaction-icon"   data-toggle="collapse" :data-target="'#collapseExample-'+index" aria-expanded="false" aria-controls="'collapseExample-'+index"></span>
              <span class="fab fa-mailchimp reaction-icon"></span>
            </div>
          </div>
          <div class="back-side">
              <!-- CURRENTLY NOTHING ON THE BACK SIDE OF THE CARD UNTIL THE CARD FLIP FEATURE CAN BE PORTED FROM PRIOR PROJECT VERSION -->
          </div>
        </div>

        <!-- this is the collapsable / togglable div for the comments section for each card -->
        <div class="collapse" :id="'collapseExample-'+index">
            <newcomment v-bind:startupcardid="startupCard.brand_id"></newcomment>

          <!-- START: TESTING MULTI COMMENT LOAD FROM FIREBASE  -->
          <comment v-bind:startupcardid="startupCard.brand_id"></comment>

          
          <!-- END: TESTING MULTI COMMENT LOAD FROM FIREBASE  -->

        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import db from './firebaseInit'
  import firebase from 'firebase'
  import CommentList from './CommentList'
  import NewComment from './NewComment'

  export default {
    name: 'feed',
    components: {
      'comment':CommentList,
      'newcomment':NewComment
    },
    data() {
      return {
        commentTextField: '',
        startupCards: []
      }
    },
    created() {
      db.collection('startupCards').orderBy('dateAdded').get().then(querySnapshot => {
        querySnapshot.forEach(doc => {
          const data = { // any data you want to pull from Firestore db on the startup cards collection is put into this data object
            'brand_id': doc.id,
            'brandTitle': doc.data().brandTitle,
            'brandHeading': doc.data().brandHeading,
            'brandDateAdded': doc.data().dateAdded,
            'brandHearts':doc.data().hearts,
            'brandLocation':doc.data().location
          }
          this.startupCards.push(data)
        })
      })


      
    },
    methods: {
        activateHeart: function(startupCard) {
            var cardID = startupCard.brand_id
            var heartValUpdate =  startupCard.brandHearts +1  // this somewhat works

            db.collection('startupCards').doc(cardID).get()
                .then(doc => {
                    if(!doc.exists){
                        console.log('doc wasnt found')
                    } else{
                        console.log('heart count: '+doc.data().hearts)
                        doc.update({hearts: heartValUpdate})
                        }
                })
            //console.log('selected company with firebase doc id of :  ' + cardID + ' with currently '+ heartValUpdate +' hearts'+  '!') // we are retuning the doc id as auto-generated by firebase in console
            //db.collection('startupCards').doc(cardID).update({
                //hearts: heartValUpdate
            //})
        }
        
    }
  }

</script>

<style scoped>
  #feed{
    background-color: #ebe9e9; 
  }
  .reaction-icon {
    font-size: 3rem;
    padding-top: 1rem;
    padding-bottom: 1rem;
    margin-left: .5rem;
    margin-right: .5rem;
    color: dodgerblue;
  }

  .reaction-list {
    display: flex;
    flex: 3;
    justify-content: space-between;
  }

  .pt-1 {
    padding-top: 1em;
  }

  .pb-1 {
    padding-bottom: 1em;
  }
  .comment-section{
      background: #ffffff;
      color: black;
      justify-content: left;    
      padding: 5px;  
  }

  .flag{
    background: rgba(0, 0, 0, 0.6);
    position: absolute;
    top: 50%;
    width: 100%;
    height: 50%;
    -webkit-clip-path: polygon(50% 50%, 100% 0, 100% 100%, 0 100%, 0 0);
    clip-path: polygon(50% 50%, 100% 0, 100% 100%, 0 100%, 0 0);
    /* -webkit-transform-style: preserve-3d;
    transform-style: preserve-3d;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    transition: 1s ease !important;
    -webkit-transition: 1s ease !important; */
  }

</style>
